# Generated by Django 5.2.3 on 2025-06-23 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_subscription_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalSubscription',
        ),
    ]
