# Generated by Django 5.0.3 on 2025-10-30 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_eventorganizer_options_and_more'),
        ('events', '0014_eventlist_is_main_list_eventlist_is_waiting_list'),
    ]

    operations = [
        # Create the intermediate table for Many-to-Many relationship
        migrations.CreateModel(
            name='EventListEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventlist')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'db_table': 'events_eventlist_events',
                'unique_together': {('eventlist', 'event')},
            },
        ),
    ]
