# Generated by Django 5.0.3 on 2025-10-30 00:01

from django.db import migrations


def migrate_existing_eventlists_to_manytomany(apps, schema_editor):
    """
    Migra tutte le EventList esistenti dalla relazione ForeignKey (event)
    alla nuova relazione Many-to-Many (events).
    
    Per ogni EventList che ha un event_id, crea una entry nella tabella
    di join EventListEvent che collega quella lista a quell'evento.
    """
    EventList = apps.get_model('events', 'EventList')
    EventListEvent = apps.get_model('events', 'EventListEvent')
    
    eventlists = EventList.objects.all()
    
    for eventlist in eventlists:
        if eventlist.event_id:  # Se la lista è collegata a un evento
            # Crea la relazione Many-to-Many
            EventListEvent.objects.create(
                eventlist=eventlist,
                event_id=eventlist.event_id
            )
    
    print(f"Migrated {eventlists.count()} EventLists to Many-to-Many relationship")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: cancella tutte le entry dalla tabella di join.
    Nota: la relazione ForeignKey esiste ancora in questo punto, quindi
    i dati originali sono preservati.
    """
    EventListEvent = apps.get_model('events', 'EventListEvent')
    EventListEvent.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_create_manytomany_eventlist_events'),
    ]

    operations = [
        migrations.RunPython(
            migrate_existing_eventlists_to_manytomany,
            reverse_migration
        ),
    ]
