# Generated by Django 5.0.3 on 2025-10-30 00:02

from django.db import migrations, models


def remove_event_fk_manually(apps, schema_editor):
    """
    Manually remove the foreign key constraint and event_id column.
    Django's automatic removal was failing due to constraint issues.
    """
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            # First, check if column exists
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE()
                AND TABLE_NAME = 'events_eventlist' 
                AND COLUMN_NAME = 'event_id'
            """)
            exists = cursor.fetchone()[0]
            
            if exists:
                # Find and drop any foreign key constraints
                cursor.execute("""
                    SELECT CONSTRAINT_NAME 
                    FROM information_schema.KEY_COLUMN_USAGE 
                    WHERE TABLE_SCHEMA = DATABASE()
                    AND TABLE_NAME = 'events_eventlist' 
                    AND COLUMN_NAME = 'event_id' 
                    AND REFERENCED_TABLE_NAME IS NOT NULL
                """)
                result = cursor.fetchone()
                
                if result:
                    fk_name = result[0]
                    # Drop the foreign key constraint
                    cursor.execute(f"ALTER TABLE events_eventlist DROP FOREIGN KEY {fk_name}")
                
                # Drop any regular indexes on event_id
                cursor.execute("""
                    SELECT INDEX_NAME 
                    FROM information_schema.STATISTICS 
                    WHERE TABLE_SCHEMA = DATABASE()
                    AND TABLE_NAME = 'events_eventlist' 
                    AND COLUMN_NAME = 'event_id'
                    AND INDEX_NAME != 'PRIMARY'
                """)
                for row in cursor.fetchall():
                    index_name = row[0]
                    cursor.execute(f"ALTER TABLE events_eventlist DROP INDEX {index_name}")
                
                # Now drop the column
                cursor.execute("ALTER TABLE events_eventlist DROP COLUMN event_id")


def add_event_fk_back(apps, schema_editor):
    """Reverse migration - add back the event_id column"""
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                ALTER TABLE events_eventlist 
                ADD COLUMN event_id INT NOT NULL
            """)
            cursor.execute("""
                ALTER TABLE events_eventlist 
                ADD CONSTRAINT events_eventlist_event_id_fk 
                FOREIGN KEY (event_id) REFERENCES events_event(id)
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_migrate_data_to_manytomany'),
    ]

    operations = [
        # Step 1: Manually remove the old ForeignKey field 'event' with SQL
        migrations.RunPython(
            remove_event_fk_manually,
            add_event_fk_back
        ),
        
        # Step 2: Add the new ManyToManyField 'events'
        migrations.AddField(
            model_name='eventlist',
            name='events',
            field=models.ManyToManyField(
                related_name='lists',
                through='events.EventListEvent',
                to='events.event',
                help_text='Eventi che utilizzano questa lista'
            ),
        ),
    ]
