# Generated by Django 5.0.3 on 2024-07-04 06:57

import django_countries.fields
import phonenumber_field.modelfields
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Passport', 'Passport'), ('Identity Card', 'Identity Card')], max_length=32)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('expiration', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalProfile',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('enabled', models.BooleanField(default=True)),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('email', models.EmailField(db_index=True, max_length=256)),
                ('email_is_verified', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('birthdate', models.DateField(null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('course', models.CharField(choices=[('Engineering', 'Engineering'), ('Architecture', 'Architecture'), ('Design', 'Design')], max_length=32, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('whatsapp', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('person_code', models.PositiveIntegerField(db_index=True, null=True)),
                ('domicile', models.CharField(max_length=256, null=True)),
                ('residency', models.CharField(max_length=256, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical profile',
                'verbose_name_plural': 'historical profiles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Matricola',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(unique=True)),
                ('exchange_end', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('email_is_verified', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('birthdate', models.DateField(null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('course', models.CharField(choices=[('Engineering', 'Engineering'), ('Architecture', 'Architecture'), ('Design', 'Design')], max_length=32, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('whatsapp', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('person_code', models.PositiveIntegerField(null=True, unique=True)),
                ('domicile', models.CharField(max_length=256, null=True)),
                ('residency', models.CharField(max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
