# Generated by Django 5.0.3 on 2024-11-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprofile",
            name="is_esner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_esner",
            field=models.BooleanField(default=False),
        ),
    ]
