# Generated by Django 5.1.3 on 2025-03-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_alter_document_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="number",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
