# Generated by Django 5.1.3 on 2025-03-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0006_delete_matricola"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprofile",
            name="matricola_expiration",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="matricola_number",
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="matricola_expiration",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="matricola_number",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
