# Generated by Django 5.1.3 on 2025-03-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0008_remove_historicalprofile_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="type",
            field=models.CharField(
                choices=[
                    ("Passport", "Passport"),
                    ("National ID Card", "National ID Card"),
                    ("Driving License", "Driving License"),
                    ("Residence Permit", "Residence Permit"),
                    ("Other", "Other"),
                ],
                max_length=32,
            ),
        ),
    ]
