# Generated by Django 5.1.3 on 2025-03-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0009_alter_document_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalprofile",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="historicalprofile",
            name="whatsapp",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="whatsapp",
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="phone_number",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="phone_prefix",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="whatsapp_number",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="whatsapp_prefix",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_prefix",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="whatsapp_number",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="whatsapp_prefix",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="type",
            field=models.CharField(
                choices=[
                    ("Passport", "Passport"),
                    ("National ID Card", "National ID Card"),
                    ("Driving License", "Driving License"),
                    ("Residency Permit", "Residency Permit"),
                    ("Other", "Other"),
                ],
                max_length=32,
            ),
        ),
    ]
