# Generated by Django 5.2.3 on 2025-06-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_historicalprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Passport', 'Passport'), ('ID Card', 'ID Card'), ('Driving License', 'Driving License'), ('Residency Permit', 'Residency Permit'), ('Other', 'Other')], max_length=32),
        ),
    ]
