# Generated by Django 5.2.3 on 2025-06-23 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_document_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalProfile',
        ),
    ]
