# Generated by Django 5.1.3 on 2025-03-18 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_initial"),
        ("profiles", "0011_alter_historicalprofile_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="additional_fields",
        ),
        migrations.RemoveField(
            model_name="event",
            name="enable_form",
        ),
        migrations.RemoveField(
            model_name="event",
            name="form_fields",
        ),
        migrations.RemoveField(
            model_name="event",
            name="profile_fields",
        ),
        migrations.RemoveField(
            model_name="event",
            name="tables",
        ),
        migrations.RemoveField(
            model_name="historicalsubscription",
            name="additional_data",
        ),
        migrations.RemoveField(
            model_name="historicalsubscription",
            name="event_data",
        ),
        migrations.RemoveField(
            model_name="historicalsubscription",
            name="form_data",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="additional_data",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="event_data",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="form_data",
        ),
        migrations.AddField(
            model_name="event",
            name="cost",
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="historicalsubscription",
            name="created_by_form",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalsubscription",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalsubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("reimbursed", "Reimbursed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="created_by_form",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscription",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("reimbursed", "Reimbursed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="EventTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=64)),
                ("capacity", models.PositiveIntegerField(default=0)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
                "unique_together": {("event", "name")},
            },
        ),
        migrations.AddField(
            model_name="historicalsubscription",
            name="table",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="events.eventtable",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="table",
            field=models.ForeignKey(
                null=True,  # Allow null temporarily
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="events.eventtable",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="EventOrganizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=True)),
                ("is_lead", models.BooleanField(default=False)),
                ("role", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizers",
                        to="events.event",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_events",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["is_lead", "id"],
                "unique_together": {("event", "profile")},
            },
        ),
    ]
