# Generated by Django 5.1.3 on 2025-03-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_fix_subscription_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="subscription_end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="subscription_start_date",
            field=models.DateField(null=True),
        ),
    ]
