# Generated by Django 5.1.3 on 2025-03-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_event_subscription_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="subscription_end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="subscription_start_date",
            field=models.DateTimeField(null=True),
        ),
    ]
