# Generated by Django 5.1.3 on 2025-03-24 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_alter_event_subscription_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="table",
        ),
        migrations.RemoveField(
            model_name="historicalsubscription",
            name="table",
        ),
        migrations.CreateModel(
            name="EventList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=64)),
                ("capacity", models.PositiveIntegerField(default=0)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lists",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
                "unique_together": {("event", "name")},
            },
        ),
        migrations.AddField(
            model_name="historicalsubscription",
            name="list",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="events.eventlist",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="list",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="events.eventlist",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="EventTable",
        ),
    ]
