# Generated by Django 5.2.5 on 2025-10-28 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_delete_historicalsubscription'),
        ('profiles', '0015_alter_profile_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventorganizer',
            options={'ordering': ['-is_lead', 'id']},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='status',
        ),
        migrations.AddField(
            model_name='event',
            name='allow_online_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='enable_form',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='form_programmed_open_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_a_bando',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_allow_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_refa_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='profile_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='eventlist',
            name='is_main_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventlist',
            name='is_waiting_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subscription',
            name='external_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='form_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subscription',
            name='form_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='sumup_checkout_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='sumup_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
