services:
  backend:
    build: ./backend
    volumes:
      - type: bind
        source: ./backend
        target: /app
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    volumes:
      - type: bind
        source: ./frontend/src
        target: /app/src
    ports:
      - "3000:3000"
  