# Generated by Django 5.2.5 on 2025-10-28 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('order', models.IntegerField(default=0, verbose_name='Ordine')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_sections_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sezione Contenuto',
                'verbose_name_plural': 'Sezioni Contenuto',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ContentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL')),
                ('color', models.CharField(default='#1976d2', max_length=7, verbose_name='Colore')),
                ('order', models.IntegerField(default=0, verbose_name='Ordine')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('action_type', models.CharField(blank=True, help_text="Es: 'open_reimbursement_modal'", max_length=50, null=True, verbose_name='Tipo Azione')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_links_created', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='content.contentsection', verbose_name='Sezione')),
            ],
            options={
                'verbose_name': 'Link Contenuto',
                'verbose_name_plural': 'Link Contenuto',
                'ordering': ['order', 'name'],
            },
        ),
    ]
