# Generated by Django 5.2.5 on 2025-10-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentlink',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='contentsection',
            name='description',
        ),
        migrations.AlterField(
            model_name='contentlink',
            name='color',
            field=models.CharField(default='#1976d2', help_text='Formato: #RRGGBB', max_length=7, verbose_name='Colore'),
        ),
        migrations.AlterField(
            model_name='contentlink',
            name='description',
            field=models.TextField(help_text='Descrizione del link', verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='contentlink',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Titolo'),
        ),
        migrations.AlterField(
            model_name='contentlink',
            name='url',
            field=models.URLField(max_length=500, verbose_name='Link/URL'),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='title',
            field=models.CharField(choices=[('LINK_UTILI', 'LINK UTILI'), ('WIKI_TUTORIAL', 'WIKI E TUTORIAL')], max_length=200, unique=True, verbose_name='Categoria'),
        ),
    ]
