# Generated by Django 5.2.5 on 2025-10-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_contentlink_action_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentlink',
            name='description',
            field=models.TextField(blank=True, help_text='Descrizione del link (opzionale)', verbose_name='Descrizione'),
        ),
    ]
