# Generated by Django 5.2.7 on 2025-11-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='closed', max_length=8)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ESNcard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'ESNcard',
                'verbose_name_plural': 'ESNcards',
            },
        ),
        migrations.CreateModel(
            name='ReimbursementRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment', models.CharField(choices=[('cash', 'Contanti'), ('paypal', 'PayPal'), ('bonifico', 'Bonifico')], max_length=16)),
                ('description', models.TextField(max_length=1024)),
                ('receipt_link', models.URLField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esncard_release_fee', models.DecimalField(decimal_places=2, default=10.0, max_digits=9)),
                ('esncard_lost_fee', models.DecimalField(decimal_places=2, default=4.0, max_digits=9)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('subscription', 'Subscription'), ('esncard', 'ESNcard'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('reimbursement', 'Reimbursement'), ('cauzione', 'Cauzione'), ('rimborso_cauzione', 'Rimborso Cauzione'), ('rimborso_quota', 'Rimborso Quota')], default='deposit', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('description', models.TextField(max_length=1024)),
                ('receipt_link', models.URLField(blank=True, max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
