# Generated by Django 5.2.7 on 2025-11-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='description',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=256),
        ),
    ]
