# Generated by Django 5.1.3 on 2025-04-28 14:54

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0003_settings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="settings",
            old_name="esncard_renewal_fee_currency",
            new_name="esncard_lost_fee_currency",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="esncard_renewal_fee",
        ),
        migrations.AddField(
            model_name="settings",
            name="esncard_lost_fee",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("4.0"),
                default_currency="EUR",
                max_digits=9,
            ),
        ),
    ]
