# Generated by Django 5.2 on 2025-05-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0005_transaction_esncard_transaction_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("subscription", "Subscription"),
                    ("esncard", "ESNcard"),
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                ],
                default="deposit",
                max_length=12,
            ),
        ),
    ]
