# Generated by Django 5.2 on 2025-05-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("treasury", "0006_alter_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="visible_to_groups",
            field=models.ManyToManyField(blank=True, to="auth.group"),
        ),
    ]
