# Generated by Django 5.2.3 on 2025-06-23 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0008_alter_account_visible_to_groups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalAccount',
        ),
    ]
