# Generated by Django 5.2.5 on 2025-10-28 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_eventorganizer_options_and_more'),
        ('treasury', '0009_delete_historicalaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='esncard',
            options={'verbose_name': 'ESNcard', 'verbose_name_plural': 'ESNcards'},
        ),
        migrations.RemoveField(
            model_name='account',
            name='balance_currency',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='esncard_lost_fee_currency',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='esncard_release_fee_currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount_currency',
        ),
        migrations.AddField(
            model_name='transaction',
            name='event_reference_manual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt_link',
            field=models.URLField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='esncard',
            name='number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='esncard_lost_fee',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='settings',
            name='esncard_release_fee',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('esncard', 'ESNcard'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('reimbursement', 'Reimbursement'), ('cauzione', 'Cauzione'), ('rimborso_cauzione', 'Rimborso Cauzione'), ('rimborso_quota', 'Rimborso Quota')], default='deposit', max_length=30),
        ),
        migrations.CreateModel(
            name='ReimbursementRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment', models.CharField(choices=[('cash', 'Contanti'), ('paypal', 'PayPal'), ('bonifico', 'Bonifico')], max_length=16)),
                ('description', models.CharField(max_length=512)),
                ('receipt_link', models.URLField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treasury.account')),
                ('reimbursement_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_request', to='treasury.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
