# Generated by Django 5.2.5 on 2026-01-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0003_alter_reimbursementrequest_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursementrequest',
            name='description',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('esncard', 'ESNcard'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('reimbursement', 'Reimbursement'), ('cauzione', 'Cauzione'), ('rimborso_cauzione', 'Rimborso Cauzione'), ('rimborso_quota', 'Rimborso Quota'), ('service', 'Service'), ('rimborso_service', 'Rimborso Service')], default='deposit', max_length=30),
        ),
    ]
