# Generated by Django 5.2 on 2025-05-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("treasury", "0007_account_visible_to_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="visible_to_groups",
            field=models.ManyToManyField(to="auth.group"),
        ),
    ]
