# Generated by Django 5.2.7 on 2025-11-02 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('email_is_verified', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('birthdate', models.DateField(null=True)),
                ('country', models.CharField(max_length=2, null=True)),
                ('course', models.CharField(choices=[('Engineering', 'Engineering'), ('Architecture', 'Architecture'), ('Design', 'Design')], max_length=32, null=True)),
                ('phone_prefix', models.CharField(max_length=10, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('whatsapp_prefix', models.CharField(max_length=10, null=True)),
                ('whatsapp_number', models.CharField(max_length=20, null=True)),
                ('person_code', models.CharField(max_length=10, null=True, unique=True)),
                ('domicile', models.CharField(max_length=256, null=True)),
                ('is_esner', models.BooleanField(default=False)),
                ('matricola_number', models.CharField(max_length=10, null=True, unique=True)),
                ('matricola_expiration', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Passport', 'Passport'), ('ID Card', 'ID Card'), ('Driving License', 'Driving License'), ('Residency Permit', 'Residency Permit'), ('Other', 'Other')], max_length=32)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('expiration', models.DateField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
