# Generated by Django 5.1.3 on 2025-03-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_historicalprofile_is_esner_profile_is_esner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="number",
            field=models.CharField(max_length=32),
        ),
    ]
