# Generated by Django 5.1.3 on 2025-03-03 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0005_alter_document_number"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Matricola",
        ),
    ]
