# Generated by Django 5.1.3 on 2025-03-09 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0007_historicalprofile_matricola_expiration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalprofile",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="historicalprofile",
            name="residency",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="residency",
        ),
    ]
