# Generated by Django 5.1.3 on 2025-03-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0010_remove_historicalprofile_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalprofile",
            name="country",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=models.CharField(max_length=2, null=True),
        ),
    ]
