# Generated by Django 5.2.3 on 2025-06-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0014_alter_profile_matricola_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
