# Generated by Django 5.2.5 on 2025-10-28 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_contentlink_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentlink',
            name='is_active',
        ),
    ]
